# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndDeploy
  displayName: Build image
  jobs:
  - job: BuildAndPushJob
    displayName: BuildAndPush
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerRegistryConnection'
        repository: 'joaoaugustomv/verificlima-backend'
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
        tags: '$(tag)'
  - job: DeployAppWeb
    displayName: Deploy App Web
    dependsOn: BuildAndPushJob
    steps:
      - task: AzureWebAppContainer@1
        inputs:
          azureSubscription: 'Assinatura do Azure 1(202ccb71-b2af-48ae-af39-021758856113)'
          appName: 'verificlima-backend-app-web'
          imageName: 'joaoaugustomv/verificlima-backend:$(tag)'
        