name: Trigger auto deployment for verificlima-backend-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'dockerfile/**'
    - '.github/workflows/verificlima-backend-container-AutoDeployTrigger-1cc4d662-b557-4023-8907-23868b6a5480.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.VERIFICLIMABACKENDCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VERIFICLIMABACKENDCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VERIFICLIMABACKENDCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/dockerfile 
          registryUrl: docker.io
          registryUsername: ${{ secrets.VERIFICLIMABACKENDCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VERIFICLIMABACKENDCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: verificlima-backend-container
          resourceGroup: VerifiClima_recursos
          imageToBuild: joaoaugustomv/verificlima-backend-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


